Implement stop application
Mitko-Kerezov/device-lib pull request #3
Opened 2017-01-30 14:12 UTC by Mitko-Kerezov

2017-01-30 17:03 UTC, TsvetanMilanov requested changes

2017-01-30 17:03 UTC, TsvetanMilanov commented on FfiSpike/FfiSpike.cpp
> +		devices[device_identifier].apps_cache[application_identifier].afc_connection;
I think this should be `afc_connection_to_close = devices[device_identifier].apps_cache[application_identifier].afc_connection;`

2017-01-30 17:03 UTC, TsvetanMilanov commented on FfiSpike/FfiSpike.cpp
> +	devices[device_identifier].apps_cache[application_identifier].afc_connection = afc_conn_p ;
Not a merge stopper but there is one unnecessary whitespace before the `;`.

2017-01-30 17:03 UTC, TsvetanMilanov commented on FfiSpike/FfiSpike.cpp
> +		std::string executable = map[application_identifier]["Path"];
I think it will be good to extract "Path" in constant since it is used more than one time.

2017-01-30 17:03 UTC, TsvetanMilanov commented on FfiSpike/GDBHelper.cpp
> +	apps_cache[application_identifier].has_initialized_gdb = true;
I think if the user just want to start an application the `apps_cache` will not have `apps_cache[application_identifier]` and `apps_cache[application_identifier].has_initialized_gdb` will throw an error. Can you add check for `apps_cache[application_identifier]` if I am right.

2017-01-31 09:30 UTC, Mitko-Kerezov commented on FfiSpike/GDBHelper.cpp
> +	apps_cache[application_identifier].has_initialized_gdb = true;
Accessing `apps_cache[application_identifier]` will immediately initialize an empty structure (e.g. containing a `NULL` pointer and a `false` boolean value). So we're okay here

2017-01-31 09:41 UTC, TsvetanMilanov approved these changes

2017-01-31 09:47 UTC, merged